# Human readable title of application.
title: Template Provider

overviewShort: The Template Crossplane Provider allows you to bootstrap your own provider.
overview: |-
  The Template Crossplane Provider is a minimal Crossplane Provider that serves
  as a starting point for building new Crossplane Providers. It is meant to be
  refactored for your use-case.
# Markdown description of this entry
readme: |
  `provider-template` is a minimal Crossplane Provider that is meant to be used
  as a template for implementing new Providers. It comes with the following features
  that are meant to be refactored:
  - A `Provider` resource type that only points to a credentials `Secret`.
  - A `MyType` resource type that serves as an example managed resource.
  - A managed resource controller that reconciles `MyType` objects and simply prints their configuration in its `Observe` method.

# Maintainer names and emails.
maintainers:
- name: Dan Mangum
  email: dan@upbound.io

# Owner names and emails.
owners:
- name: Dan Mangum
  email: dan@upbound.io

# Human readable company name
company: Crossplane

# Primary category describing this stack
category: Infrastructure

# Type of package: Provider, Stack, or Application
packageType: Provider

# Keywords that describe this application and help search indexing
keywords:
- "template"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplanebook.github.io"
source: "https://github.com/crossplanebook/provider-template"

# RBAC ClusterRoles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'
- crd: '*.workload.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0